### PR TITLE
BUG Creating folder doesn't refresh (fixes #209)

### LINKED ISSUE #209: BUG Creating folder doesn't refresh UI
After creating a folder the json response for the new folder is returned, but the UI won't display this until a refresh.

`{"ParentID":0,"ID":3,"Filename":"Uploads\/"}` for instance.

I would expect "Uploads" to appear beside the folder here.

image

### PR DESCRIPTION
**Pull request by chillu**
Regression from react-router work. Needed to factor out Gallery.js promptFolderName() in order to make it mockable. Also fixed _t() call use, and removed the leftover `SET_FOLDER` and `SET_FILE` actions.

Uses a promise returned from a thunk in order to hook into the createFolder logic. This is a technique documented on https://github.com/gaearon/redux-thunk. Ideally this view refresh would happen through action creator chaining, but that's not possible because the `SET_FOLDER` action can no longer be used alongside the route param (see https://github.com/silverstripe/silverstripe-framework/issues/5711#issuecomment-240367840).

### CODE REVIEW

File: client/lang/en.js [hunk 1]
```diff
@@ -40,6 +40,7 @@ if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
     "AssetAdmin.LASTEDIT": "Last changed",
     "AssetAdmin.LOADMORE": "Load more",
     "AssetAdmin.NOITEMSFOUND": "No items found",
+    "AssetAdmin.PROMPTFOLDERNAME": "Folder name (or blank to cancel)",
```
Comment (flamerohr) [inline client/lang/en.js]: how about have this a bit more instructive like:
> Please enter a folder name (or blank to cancel)

File: client/src/containers/Gallery/Gallery.js [hunk 2]
```diff
@@ -246,15 +246,18 @@ export class Gallery extends Component {
    *
    * @param object event - Click event.
    */
-  handleCreateFolder() {
+  handleCreateFolder(event) {
```
Comment (flamerohr) [inline client/src/containers/Gallery/Gallery.js]: although it's not an issue due to the button being `type="button"`, add missing `event.preventDefault();` call?

File: client/src/containers/Gallery/Gallery.js [hunk 3]
```diff
@@ -289,6 +292,13 @@ export class Gallery extends Component {
     }
   }
 
+	/**
+   * @return String
+   */
+  promptFolderName() {
+    return prompt(i18n._t('AssetAdmin.PROMPTFOLDERNAME'));
```
Comment (flamerohr) [inline client/src/containers/Gallery/Gallery.js]: what is the benefit of moving this line to a new function? It seemed more intuitive to have this in the `handleCreateFolder` function because prompt is quite unique for javascript.

Comment (chillu) [inline client/src/containers/Gallery/Gallery.js]: Yeah "test-driven apis" - not great, but I couldn't see any other way. `handleCreateFolderName()` is already fairly atomic as far as passed-in props go for the component.

File: client/src/containers/Gallery/Gallery.js (hunk 2 above)
Comment (chillu) [inline client/src/containers/Gallery/Gallery.js]: Good call, done!

File: client/lang/en.js (hunk 1 above)
Comment (chillu) [inline client/lang/en.js]: Just taken over the existing label, but changed it - thanks for your attention to detail there!

File: client/src/containers/Gallery/Gallery.js (hunk 3 above)
Comment (tractorcow) [inline client/src/containers/Gallery/Gallery.js]: Not a blocker for this PR, but can we make sure to include default text for JS translation strings here as well? It provides a reference for the user, as well as the to-be-developed js text collector.

File: client/src/containers/Gallery/tests/Gallery-test.js [hunk 4]
```diff
@@ -55,292 +53,28 @@ describe('Gallery', () => {
     };
   });
 
-  describe('handleSuccessfulUpload', () => {
```
Comment (tractorcow) [inline client/src/containers/Gallery/tests/Gallery-test.js]: Did we need to delete all these tests?
