### PR TITLE
BUG Ensure that file replacement checks for clashes with existing files

### LINKED ISSUE #369: UploadFile api does not check for conflicts
Paraphrasing @tractorcow 
This is an issue where saving a file in asset-admin wasn't safely ensuring the name was unique
The asset store does a file-exists uniqueness check, but there's a case where a File dataobject with a missing physical file would not trigger a conflict.

So we need to enforce uniqueness against:
- Filename against all File dataobjects
- Filename and Hash against the actual file store

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #369

Requires https://github.com/silverstripe/silverstripe-framework/pull/6527

Note: Updated so that existing files are detected to avoid duplication, as per discussion with @sminnee

### CODE REVIEW

File: client/src/components/PreviewImageField/PreviewImageField.js [hunk 1]
```diff
@@ -166,10 +168,8 @@ class PreviewImageField extends Component {
       this.props.onAutofill('FileHash', json.Hash);
       this.props.onAutofill('FileVariant', json.Variant);
 
-      const oldExt = getFileExtension(this.props.data.url);
-      const newExt = getFileExtension(json.Filename);
-      if (oldExt !== newExt) {
-        // name field to autofill if extension has changed
+      // If server has requested a filename change, modify it here
+      if (json.Name) {
```
Comment (flamerohr) [inline client/src/components/PreviewImageField/PreviewImageField.js]: This can have the undesired effect of replacing the Name value an edited Name field with the original value? It's not the best user experience.

File: code/Controller/AssetAdmin.php [hunk 2]
```diff
@@ -250,28 +253,57 @@ public function apiCreateFile(HTTPRequest $request)
...
+        /** @var File $file */
+        $file = File::get()->byID($data['ID']);
+        if (!$file) {
+            return new HTTPResponse('File not found', 404);
+        }
+        $folder = $file->ParentID ? $file->Parent()->getFilename() : '/';
+
+        // If extension is the same, attempt to re-use existing name
+        if (File::get_file_extension($tmpFile['name']) === $file->getExtension()) {
+            $tmpFile['name'] = $file->Name;
```
Comment (flamerohr) [inline code/Controller/AssetAdmin.php]: rather than using the Name saved in the database, I wonder if the component could send the API the current value of the field on the form?

**Comment by tractorcow** [comment]
Updated based on feedback.

Note that framework PR https://github.com/silverstripe/silverstripe-framework/pull/6527 is now required for this fix.

File: client/src/components/PreviewImageField/PreviewImageField.js (hunk 1 above)
Comment (tractorcow) [inline client/src/components/PreviewImageField/PreviewImageField.js]: I've changed it so that the current Name is always posted back, so that json.Name will reflect the current value, unless explicitly changed.

File: code/Controller/AssetAdmin.php (hunk 2 above)
Comment (tractorcow) [inline code/Controller/AssetAdmin.php]: Done.

File: tests/behat/features/replace-file.feature [hunk 3]
```diff
@@ -14,24 +15,38 @@ Feature: Replace a file with a new file
...
+  Scenario: I upload a new file into the file I have open
     When I attach the file "testfile.jpg" to dropzone "PreviewImage"
       And I wait for 1 second
     Then I should see a ".preview__toolbar-button--remove" element
       And I should see a ".preview__message--success" element
-      And I press the "Save" button
-      And I wait for 1 second
+      And the "Name" field should contain "file1.jpg"
+    When I press the "Save" button
+      And I wait for 2 seconds
```
Comment (chillu) [inline tests/behat/features/replace-file.feature]: Not too happy about manual waits here, but it's just following a bad precedent. We need to work out if a `fetch()` is in progress through Behat feature context

Comment (tractorcow) [inline tests/behat/features/replace-file.feature]: It's annoying I know, but we need a better wait-until-ready solution for behat.

Comment (tractorcow) [inline tests/behat/features/replace-file.feature]: It's annoying I know, but we need a better wait-until-ready solution for behat.

**Comment by tractorcow** [comment]
I can't reproduce the composer issue locally; Downgrading to 1.3.1 to see if it's due to the recent composer release.

**Comment by tractorcow** [comment]
I've raised https://github.com/composer/composer/issues/6115 to investigate the possible regression in composer 1.3.2.

I suspect that the issue might be due to asset-admin dependency in the PR branch and the one cached by packagist differing.

I've raised https://github.com/silverstripe/silverstripe-asset-admin/pull/378, and suspect that force-merging this (with a broken build) and then updating packagist may resolve the issue. It can't help to experiment. :)

**Comment by tractorcow** [comment]
I've force-merged https://github.com/silverstripe/silverstripe-asset-admin/pull/378 and updated packagist to determine if the issue lies between travis and packagist (which could explain why I couldn't resolve the issue locally).

**Comment by tractorcow** [comment]
For some reason that issue resolved itself, yet without leaving behind any explanation as to why it was broken. :)

**Comment by tractorcow** [comment]
Only failure now is the behat failure, i.e. a real one. However this already exists prior to this PR. (siiigh).
